# Generated by Django 2.2 on 2020-12-04 17:42

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datetest',
            fields=[
                ('date', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('points', models.IntegerField(null=True)),
                ('gold', models.IntegerField(null=True)),
                ('gems', models.IntegerField(null=True)),
                ('expire_date', models.DateField(null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('font_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('studentname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], default='2', max_length=2)),
                ('School', models.CharField(default='大同國小', max_length=30, null=True)),
                ('SchoolId', models.IntegerField(default=4576)),
                ('photo', models.ImageField(blank=True, default='naa.png', null=True, upload_to='')),
                ('account', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=255)),
                ('birthday', models.IntegerField(default=0)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('BMI', models.FloatField(null=True)),
                ('Class', models.CharField(max_length=30, null=True)),
                ('Section', models.CharField(max_length=30, null=True)),
                ('RollNo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webdata',
            fields=[
                ('studentname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lesson1finish', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('lesson2finish', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('lesson3finish', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('is_lesson1_part1', models.BooleanField(default=False)),
                ('is_lesson1_part2', models.BooleanField(default=False)),
                ('is_lesson2_part1', models.BooleanField(default=False)),
                ('is_lesson2_part2', models.BooleanField(default=False)),
                ('is_lesson3_part1', models.BooleanField(default=False)),
                ('is_lesson3_part2', models.BooleanField(default=False)),
                ('chart_type', models.CharField(choices=[('pie', 'Pie'), ('bar', 'Bar'), ('line', 'Line')], default='line', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField(default=0)),
                ('stepsgoal', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('caloriesgoal', models.IntegerField(default=0)),
                ('totaldistance', models.IntegerField(default=0)),
                ('heartmin', models.IntegerField(default=0)),
                ('heartmax', models.IntegerField(default=0)),
                ('hearttotal', models.IntegerField(default=0)),
                ('recordNum', models.IntegerField(default=0)),
                ('hasvalue', models.BooleanField(default=False)),
                ('sleepscore', models.FloatField(default=0.0)),
                ('act_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test001.StudentProfile')),
            ],
        ),
    ]
