# Generated by Django 3.0.7 on 2020-06-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('sleep', models.IntegerField()),
                ('walk', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('avg_monday', models.IntegerField()),
                ('avg_tuesday', models.IntegerField()),
                ('avg_wednesday', models.IntegerField()),
                ('avg_thursday', models.IntegerField()),
                ('avg_friday', models.IntegerField()),
                ('avg_saturday', models.IntegerField()),
                ('avg_sunday', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
