# Generated by Django 2.2 on 2020-12-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together={('act_date', 'user')},
        ),
    ]
