# Generated by Django 3.0.7 on 2020-06-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test001Bandsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.BigIntegerField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.BigIntegerField(blank=True, null=True)),
                ('male', models.FloatField(blank=True, null=True)),
                ('female', models.FloatField(blank=True, null=True)),
                ('data_time', models.TextField(blank=True, null=True)),
                ('userid', models.BigIntegerField(blank=True, null=True)),
                ('heart_recordnum', models.BigIntegerField(blank=True, db_column='heart_recordNum', null=True)),
                ('heart_max', models.BigIntegerField(blank=True, null=True)),
                ('heart_min', models.BigIntegerField(blank=True, null=True)),
                ('heart_total', models.BigIntegerField(blank=True, null=True)),
                ('sleep_deepsleeptime', models.BigIntegerField(blank=True, db_column='sleep_deepSleepTime', null=True)),
                ('sleep_lightsleeptime', models.BigIntegerField(blank=True, db_column='sleep_lightSleepTime', null=True)),
                ('sleep_awaketime', models.BigIntegerField(blank=True, db_column='sleep_awakeTime', null=True)),
                ('sleep_score', models.FloatField(blank=True, null=True)),
                ('sleep_waketimes', models.BigIntegerField(blank=True, db_column='sleep_wakeTimes', null=True)),
                ('activity_totalsteps', models.BigIntegerField(blank=True, db_column='activity_totalSteps', null=True)),
                ('activity_totalcalories', models.BigIntegerField(blank=True, db_column='activity_totalCalories', null=True)),
                ('activity_totaldistances', models.BigIntegerField(blank=True, db_column='activity_totalDistances', null=True)),
                ('activity_moststeps', models.BigIntegerField(blank=True, db_column='activity_mostSteps', null=True)),
                ('sh150_light', models.BigIntegerField(blank=True, null=True)),
                ('sh150_moderate', models.BigIntegerField(blank=True, null=True)),
                ('sh150_vigorous', models.BigIntegerField(blank=True, null=True)),
                ('hasvalue', models.IntegerField(blank=True, db_column='hasValue', null=True)),
            ],
            options={
                'db_table': 'test001_bandsdata',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Bandsdata',
        ),
    ]
