# Generated by Django 2.2 on 2020-12-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0002_auto_20201205_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='caloriesgoal',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='stepsgoal',
            field=models.IntegerField(default=1),
        ),
    ]
