# Generated by Django 3.0.7 on 2020-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0003_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostmanDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(null=True)),
                ('content', models.CharField(max_length=20000)),
            ],
        ),
    ]
