# Generated by Django 3.0.7 on 2020-06-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0003_auto_20200606_1936'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bandsdata',
            table='bandsdata',
        ),
    ]
