# Generated by Django 3.0.7 on 2020-06-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0004_auto_20200606_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bandsdata',
        ),
    ]
