# Generated by Django 2.2 on 2020-09-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0004_postmandb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostmanDb',
        ),
    ]
