# Generated by Django 2.2 on 2020-09-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0007_auto_20200930_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
