# Generated by Django 3.0.7 on 2020-06-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0007_bandsdata2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bandsdata2',
        ),
    ]
