# Generated by Django 3.0.7 on 2020-06-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0008_delete_bandsdata2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandsdata',
            options={},
        ),
    ]
