# Generated by Django 3.0.7 on 2020-06-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0009_auto_20200608_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandsdata',
            options={'managed': False},
        ),
    ]
