# Generated by Django 2.2 on 2020-10-06 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('test001', '0010_auto_20201006_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], default='1', max_length=2)),
                ('photo', models.ImageField(blank=True, default='images/avatar_male.png', null=True, upload_to='')),
                ('account', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=255)),
                ('birthday', models.DateField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('BMI', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
