# Generated by Django 3.0.7 on 2020-06-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0010_auto_20200608_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='table001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=100)),
                ('heart_rate', models.IntegerField(max_length=10, null=True)),
                ('sleep_rate', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='bandsdata',
            table='test001_bandsdata',
        ),
    ]
