# Generated by Django 3.0.7 on 2020-06-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0011_auto_20200608_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table001',
            name='heart_rate',
            field=models.IntegerField(null=True),
        ),
    ]
