# Generated by Django 2.2 on 2020-10-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0012_auto_20201006_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, default='avatar_male.png', null=True, upload_to=''),
        ),
    ]
