# Generated by Django 3.0.7 on 2020-06-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0012_auto_20200608_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='banddata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('male', models.TextField(null=True)),
                ('female', models.TextField(null=True)),
                ('data_time', models.TextField(null=True)),
                ('userid', models.IntegerField(null=True)),
                ('heart_recordnum', models.IntegerField(null=True)),
                ('heart_max', models.IntegerField(null=True)),
                ('heart_min', models.IntegerField(null=True)),
                ('heart_total', models.IntegerField(null=True)),
                ('sleep_deepsleeptime', models.IntegerField(null=True)),
                ('sleep_lightsleeptime', models.IntegerField(null=True)),
                ('sleep_awaketime', models.IntegerField(null=True)),
                ('sleep_score', models.FloatField(null=True)),
                ('sleep_waketimes', models.IntegerField(null=True)),
                ('activity_totalsteps', models.IntegerField(null=True)),
                ('activity_totalcalories', models.IntegerField(null=True)),
                ('activity_totaldistances', models.IntegerField(null=True)),
                ('activity_moststeps', models.IntegerField(null=True)),
                ('sh150_light', models.IntegerField(null=True)),
                ('sh150_moderate', models.IntegerField(null=True)),
                ('sh150_vigorous', models.IntegerField(null=True)),
                ('hasvalue', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bandsdata',
        ),
    ]
