# Generated by Django 3.0.7 on 2020-06-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0013_auto_20200608_0642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table001',
        ),
    ]
