# Generated by Django 2.2 on 2020-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0013_auto_20201006_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='today_calories',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='today_sleep',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='today_steps',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='yesterday_calories',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='yesterday_sleep',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='yesterday_steps',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, default='naa.png', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='DailyActivity',
        ),
    ]
