# Generated by Django 2.2 on 2020-10-06 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('test001', '0014_auto_20201006_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('studentname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('step', models.IntegerField(null=True)),
                ('stepgoal', models.IntegerField(null=True)),
                ('stepvalue', models.IntegerField(null=True)),
                ('calories', models.IntegerField(null=True)),
                ('caloriesgoal', models.IntegerField(null=True)),
                ('caloriesvalue', models.IntegerField(null=True)),
                ('distance', models.IntegerField(null=True)),
                ('distancegoal', models.IntegerField(null=True)),
                ('distancevalue', models.IntegerField(null=True)),
                ('totalSteps', models.IntegerField(null=True)),
                ('totalCalories', models.IntegerField(null=True)),
                ('totalDistances', models.IntegerField(null=True)),
                ('hasValue', models.BooleanField(default=False)),
                ('goalSteps', models.IntegerField(null=True)),
                ('stride', models.IntegerField(null=True)),
                ('goalCalories', models.IntegerField(null=True)),
                ('heartRateSyncDate', models.DateField(null=True)),
                ('sleepSyncDate', models.DateField(null=True)),
                ('activitySyncDate', models.DateField(null=True)),
                ('mostStepsDate', models.DateField(null=True)),
                ('mostStepsValue', models.IntegerField(null=True)),
                ('achieveDays', models.IntegerField(null=True)),
                ('sleepScore', models.FloatField(null=True)),
                ('heartRatemax', models.FloatField(null=True)),
                ('heartRatemin', models.FloatField(null=True)),
                ('heartRateavg', models.FloatField(null=True)),
                ('date', models.IntegerField(null=True)),
                ('state', models.IntegerField(null=True)),
            ],
        ),
    ]
