# Generated by Django 3.0.7 on 2020-06-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0015_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
