# Generated by Django 2.2 on 2020-10-06 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test001', '0016_auto_20201006_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdata',
            name='chart_type',
            field=models.CharField(choices=[('pie', 'Pie'), ('bar', 'Bar'), ('line', 'Line')], default='line', max_length=5),
        ),
        migrations.AddField(
            model_name='webdata',
            name='studentname',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
