# Generated by Django 3.0.7 on 2020-06-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0017_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('used', 'used'), ('expired', 'expired')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='reward',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
