# Generated by Django 2.2 on 2020-10-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0018_auto_20201007_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='is_today_calories',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='is_today_sleep',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='is_today_steps',
        ),
    ]
