# Generated by Django 3.0.7 on 2020-06-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0018_auto_20200611_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='banddata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test001.banddata'),
        ),
        migrations.AddField(
            model_name='workout',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test001.Reward'),
        ),
    ]
