# Generated by Django 2.2 on 2020-10-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0019_auto_20201007_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='is_today_calories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='is_today_sleep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='is_today_steps',
            field=models.BooleanField(default=False),
        ),
    ]
