# Generated by Django 2.2 on 2020-10-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0020_auto_20201007_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='today_steps',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='yesterday_steps',
            field=models.FloatField(default=0, null=True),
        ),
    ]
