# Generated by Django 3.0.7 on 2020-06-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0020_auto_20200611_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='tags',
        ),
        migrations.AddField(
            model_name='banddata',
            name='tags',
            field=models.ManyToManyField(to='test001.Tag'),
        ),
    ]
