# Generated by Django 2.2 on 2020-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0021_auto_20201007_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='achieveDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='activitySyncDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='caloriesgoal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='caloriesvalue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='distancegoal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='distancevalue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='goalCalories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='goalSteps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='hasValue',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='heartRateSyncDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='heartRateavg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='heartRatemax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='heartRatemin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='mostStepsDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='mostStepsValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='sleepScore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='sleepSyncDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='stepgoal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='stepvalue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='stride',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='totalCalories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='totalDistances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='totalSteps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
