# Generated by Django 3.0.7 on 2020-06-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0021_auto_20200611_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='gems',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
