# Generated by Django 3.0.7 on 2020-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0022_auto_20200611_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='font_size',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
