# Generated by Django 3.0.7 on 2020-06-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0023_reward_font_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamkang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.TextField(max_length=100, null=True)),
                ('branches', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
