# Generated by Django 2.2 on 2020-10-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test001', '0023_auto_20201008_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='RollNo',
            field=models.IntegerField(default=0),
        ),
    ]
